# creates a base image from conda
FROM continuumio/miniconda3
SHELL ["/bin/bash", "-c"]
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y build-essential

# conda env export > environment.yaml
RUN mkdir /tools
WORKDIR /tools
# COPY environment.yaml strainline.sh . 
COPY environment.yaml daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz Strainline.tar.gz . 
RUN . /opt/conda/bin/activate && \
    conda config --add channels https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/ && \
    conda config --add channels https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/ && \
    conda config --set show_channel_urls yes && \
    conda env create -n strainline -f environment.yaml && \
    conda clean -a && \
    # wget https://github.com/gt1/daccord/releases/download/0.0.10-release-20170526170720/daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz && \
    tar -zvxf daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz && \
    tar -zvxf Strainline.tar.gz && \
    ln -fs /tools/daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu/bin/daccord /opt/conda/envs/strainline/bin/daccord && \
# RUN git clone https://github.com/HaploKit/Strainline.git && \
    rm daccord-0.0.10-release-20170526170720-x86_64-etch-linux-gnu.tar.gz Strainline.tar.gz environment.yaml
ENV PATH=/opt/conda/envs/strainline/bin/:$PATH
ENV PATH=/tools/Strainline/src/:$PATH

# docker run -it --rm -v $PWD:/wd -w /wd -v /var/run/docker.sock:/var/run/docker.sock strainline /bin/bash
# docker run -v $PWD:$PWD -w $PWD strainline strainline.sh -i reads.fa -o out -p pb -k 20 -t 16
# docker run -v $PWD:$PWD -w $PWD strainline strainline.sh -t 16 -i barcode12.non.host.fasta -o docker_barcode12_strainline_out -p ont --minTrimmedLen 200 --minSeedLen 1000 --iter 3 --minOvlpLen 200 --minIdentity 0.95 --maxLD 0.01  --maxGD 0.02
# docker run -v $PWD:$PWD -w $PWD strainline strainline.sh -t 16 -k 200 -i barcode04.non.host.fasta -o June09_barcode04_strainline_out -p ont --minSeedLen 1000 --minTrimmedLen 200 --minOvlpLen 300
